### ISSUE TITLE
Windowing values and labels

### ISSUE THREAD

**Issue by agirault** [Kitware/paraview-glance#111]
1. Window/Level is not the correct term. The proper term is Windowing, and the variables that are handled are window width (not color window) and window level (not color level). See https://radiopaedia.org/articles/windowing-ct.

2. ~~The values in Glance are currently ranging from 0 to 255. The correct values should be width between `0` and `maxScalarValue - minScalarValue` and level between `minScalarValue` and `maxScalarValue`. See [VolumeRepresentationProxy](https://github.com/Kitware/vtk-js/blob/a64945ee2cd138736e4d0bb34f9de1daeb92a5b5/Sources/Proxy/Representations/VolumeRepresentationProxy/index.js#L56-L68) and [SliceRepresentationProxy](https://github.com/Kitware/vtk-js/blob/a64945ee2cd138736e4d0bb34f9de1daeb92a5b5/Sources/Proxy/Representations/SliceRepresentationProxy/index.js#L65-L77).~~ Which is fine for unsigned char data with min =0 and max = 255 !

**Comment by jourdain** [comment]
For the 2 we show the correct value since minScalarValue = 0 and maxScalarValue = 255.

**Comment by agirault** [comment]
Indeed! I didn't realize it was unsigned char, I should have checked first.
