### ISSUE TITLE
Crop widget interaction sticks

### ISSUE THREAD

**Issue by zachmullen** [Kitware/paraview-glance#114]
Steps:

* Load volume, use crop widget, mouse drag one corner to execute a crop.
* Stop mouse drag, crop occurs.

Problem: though the mouse drag has stopped, the widget still behaves as though the mouse is down. Sometimes it takes several clicks to get out of this state.

**Comment by jourdain** [comment]
I've noticed that as well sometime.
I was wondering if the listener I put to activate the view on click was eating the event. 
Didn't get a chance to investigate
