### ISSUE TITLE
Global css pollution

### ISSUE THREAD

**Issue by zachmullen** [Kitware/paraview-glance#119]
There are [some CSS rules](https://github.com/Kitware/paraview-glance/blob/955d79674be5c927866a5c4ecf2322e59cc514eb/src/components/core/Datasets/style.css#L38-L40) that end up modifying the CSS globally in ways that can break downstream styling. A small experiment I did makes it look like `scoped` and `module` do not work together on the same `style` tag in vue, so it might be best to move the global things out of the modular CSS and into a second `style` tag with the `scoped` attribute.

**Comment by floryst** [comment]
Fixed. There are now no global CSS rules that overwrite classes outside of the application.
