### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by doczoidberg** [Kitware/paraview-glance#125]
I did as described:
```
$ git clone https://github.com/Kitware/paraview-glance.git
$ cd paraview-glance/
$ npm install
$ npm run start
```
But I get the error:
```
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose stack Error: missing script: start
...
```

**Comment by floryst** [comment]
Ah, that's the old command from legacy Glance. I've updated the docs. You should be running `npm run dev`. If you get an error about some glob-related issue, you can either pull the latest Glance (when #127 is merged in) or run `npm run build` first.

**Comment by doczoidberg** [comment]
`npm run build` throws thousands of:
`0:3   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`

and 

```
C:\tests\paraview-glance\paraview-glance>npm run dev

> paraview-glance@0.0.0-semantically-release dev C:\tests\paraview-glance\paraview-glance
> webpack-dev-server --config build/webpack.dev.config.js

(node:2360) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
i ｢wds｣: Project is running at http://0.0.0.0:9999/
```

but I get a 404 on `http://0.0.0.0:9999/`

**Comment by floryst** [comment]
I see, you're building on Windows and our linter is complaining about newline differences. I will add a fix to our linter rules for this.

**Comment by floryst** [comment]
#128 should fix your linebreak-style issues. Once `npm run build` doesn't complain, `npm run dev` should work just fine.

**Comment by doczoidberg** [comment]
yes it works now! thank you!
