### ISSUE TITLE
Demo data does not reproduce full lookup table state shown in screenshot

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/paraview-glance#131]
For example, tooth.nrrd does not have the right range on the lookup when you first open it from the sample datasets. This is the initial view:

![image](https://user-images.githubusercontent.com/81305/42340766-e44a904a-805e-11e8-9068-a27c9748ef20.png)

**Comment by floryst** [comment]
This is related to issue #104, as we need a way to set camera/lut/etc. state.

**Comment by floryst** [comment]
Fixed with #138
