### ISSUE TITLE
Add "take screenshot" button to screenshots panel

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/paraview-glance#134]
It seems logical to add the "take screenshot" camera button to the screenshots panel. It is odd to expand the panel (initially empty) and have no controls or instructions on how to populate it.

Another option (if we only want the screenshot button in one place) is to have a default empty view to direct people to the icon at the bottom to take a screenshot. See http://emptystat.es/

**Comment by floryst** [comment]
That seems like a good idea. I'll add a button that will open the screenshot box for the active view.

+1 to the empty state filler.
