### ISSUE TITLE
Load data from script

### ISSUE THREAD

**Issue by faustomilletari** [Kitware/paraview-glance#182]
Hello,

I would like to ask some help regarding the following problem.

I have a File in the variable `file` which represents an MHA volume.

```
var arraybuf = base64ToBuffer(responses[i].content)
var blob = new Blob( [arraybuf], { type: 'text/plain' } )
var file = new File([blob], "labels.mha");
```
I would like to add to this code the necessary lines to load the file into paraview glance. I have tried to dig into the source to understand how this is done normally but I didn't have much success.

Can any of you help a little bit with it and give me some useful pointers to solve the problem?

so far I can do `ReaderFactory.loadFiles([file])` which doesn't error but doesn't make my data visible in glance either...

Many thanks,

Fausto

**Comment by jourdain** [comment]
```
const {
  vtkReader,
  parseMethod,
  fileNameMethod,
  sourceType,
} = Glance. getReader('labels.mha');

const reader = vtkReader.newInstance();
reader[fileNameMethod]('labels.mha');
reader[parseMethod](arraybuf);

Glance. registerReadersToProxyManager([{
  name: 'labels.mha',
  reader, 
  sourceType,
}], proxyManager);
```

But I need to had a couple change to the code so you can call `getReader` and `proxyManager`.

**Comment by jourdain** [comment]
Since you have a `file`, you might be able to do that as well

```
Glance
  .readFile(file)
  .then((reader) => {
    Glance.registerReadersToProxyManager([reader], glanceInstance.proxyManager);
  });
```

**Comment by faustomilletari** [comment]
And, in order to get Glance I should simply do const Glance = (typeof window === 'undefined' ? {} : window).Glance;

Do you think that might work?

**Comment by jourdain** [comment]
window.Glance should do the trick...

**Comment by faustomilletari** [comment]
Many thanks! And sorry for being a bit naive, but I just started with js

I have tried to invoke readFile(file) but this error appears
```
TypeError: window.Glance.readFile is not a function
``` 

should I maybe use the readFile from the reader factory?

**Comment by jourdain** [comment]
We need to extend that list:

https://github.com/Kitware/paraview-glance/blob/master/src/app.js#L22-L30

**Comment by faustomilletari** [comment]
I understand now :) many thanks!!

I have solved in this way

```
      var arraybuf = base64ToBuffer(responses[i].content)
      var blob = new Blob( [arraybuf], { type: 'text/plain' } )
      var file = new File([blob], "labels.mha");

      this.Glance.loadFiles([file])
      .then((readers) => {
        this.Glance.registerReadersToProxyManager(readers, this.proxyManager);
      });
```

**Comment by jourdain** [comment]
Yes that was the trick...

**Comment by faustomilletari** [comment]
I was thinking... I have written a vtkDataset to ITK image conversion script and I'm able to get MHA encoded volumes (in base 64 encoding and as files) do you think it would be worth to put some work to add a "Download" button for datasets next to the "delete" button? 

I don't know much of JS so I don't know how to do this thing but I can send you some pieces of code if there is interest...

**Comment by jourdain** [comment]
I think that could be interesting but will only be available for data that we have a Writer for. And we should not limit the output to MHA. 

On a side note, why write a dataset that we've loaded. That would make more sense if we start enabling some processing to create new datasets...

**Comment by faustomilletari** [comment]
I need to write an mha, or at least get a buffer of the file itself, because I transfer that to a remote service for deep learning inference. The remote service expects a base64 encoded mha file (and other stuff. More info on tomaat.cloud an open source project for dl inference in the cloud). 

The response arrives also in that format. Gets loaded (thanks to you and your help) and displayed. It would be cool to be able to download it.

Surely if people use paraview glance only to visualize data they have then it doesn't make sense to be able to download data.

Regards,

Fausto Milletarì

**Comment by jourdain** [comment]
It make sense to access data that was generated on the server side...

**Comment by faustomilletari** [comment]
With itk file formats it's pretty easy to have different types. Other file formats are something I'm really unfamiliar with...
