### ISSUE TITLE
Colormaps of different data get mixed up

### ISSUE THREAD

**Issue by faustomilletari** [Kitware/paraview-glance#184]
Hello,

I'm encountering an issue where I have two datasets and I apply a different color map to each of them. unfortunately the colormap gets applied to both and this is particularly problematic when the datasets are very different (not the same modality) but aligned and have different ranges. 

Do you think a solution can be found?

**Comment by jourdain** [comment]
This is expected especially for fields like pressure, temperature...
You want to make sure we use the same scale. But for ImageData from medical the name of the array is usually missing and we picked a name like `Scalars`, but maybe when loading data from ITK we should probably generate a unique array name so this conflicting field name would not happen...

**Comment by faustomilletari** [comment]
I understand now! Okay any pointer about how to possibly solve for medical data? Where should I look in the code?

**Comment by jourdain** [comment]
https://github.com/Kitware/vtk-js/blob/master/Sources/Common/DataModel/ITKHelper/index.js#L54
https://github.com/Kitware/vtk-js/blob/master/Sources/IO/Misc/ITKImageReader/index.js#L45

**Comment by faustomilletari** [comment]
ouch. that won't be easy to solve...

**Comment by jourdain** [comment]
I'll do it...

**Comment by faustomilletari** [comment]
would you suggest that after the vtk pull request is merged I just install vtk again via npm install git+<url vtk-js repo>?

**Comment by jourdain** [comment]
on your fork bump the vtk.js dependency. Glance/master will catchup but probably next week.
