### ISSUE TITLE
Nifty file format

### ISSUE THREAD

**Issue by faustomilletari** [Kitware/paraview-glance#189]
Hello,

when I try to load nii or nii.gz files I receive an error stating that there is "no reader mapping" for such file format. Do we have support for these files already or will this be tackled in a future pull request?

**Comment by floryst** [comment]
Nifty isn't supported by vtkjs, and I think they should be supported by itkjs. You should check with itkjs docs to make sure.

**Comment by faustomilletari** [comment]
There is also a niftyreader js

Maybe one could make use of that. One would need to write a function simile to the one converting itk images to vtk I think...

Fausto Milletarì

**Comment by thewtex** [comment]
Yes, itk.js supports Nifti.  We should update the docs and code so it identifies `.nii.gz`, too. I don't see where in the code ParaView Glance associates with extensions...

**Comment by jourdain** [comment]
here: https://github.com/Kitware/paraview-glance/blob/master/externals/ITKReader/index.js#L9

**Comment by thewtex** [comment]
Addressed in #196

**Comment by thewtex** [comment]
@faustomilletari thanks for the report. @jourdain addressed this in #198
