### ISSUE TITLE
Build new custom VTK.js application 

### ISSUE THREAD

**Issue by BotellaA** [Kitware/paraview-glance#215]
I would like to create a VTK.js application using vue.js as my framework and vuetify to customize the entire UI according my needs. I see that one of the purposes of Paraview-Glance is to "serve as a foundation for building custom web-based visualization applications".

However, I am not sure what is the best approach:

- Fork the project or at least start from it and the modify the code to build my own app
- Add paraview-glance as a dependency and try to import pieces of your code (if they can be imported independently)

What would be your recommandation? Maybe there is another way.
Thanks a lot for your help and your work

**Comment by jourdain** [comment]
I think you should use ParaView-Glance as a reference unless you plan to re-use pieces of the Glance ui for which you can import.

**Comment by BotellaA** [comment]
Ok, thanks for your answer.
