### ISSUE TITLE
How to combine server-side processing with glance?

### ISSUE THREAD

**Issue by BotellaA** [Kitware/paraview-glance#220]
I am looking at ParaViewWeb and Visualizer and I was wondering if we could combine in the same view the two features: 
1) local rendering in the Vue front-end using vtk-js
2) server-side processing using ParaViewWeb.

I read the several documentations and websites you made, but I still do not know where to start and if the vtkProxyManager or vtkViewProxy can handle this.

Do you have any advises on this topic and if it is even possible?

**Comment by jourdain** [comment]
We've done exactly what you describe with [ParaView Lite](https://kitware.github.io/paraview-lite/).

**Comment by jourdain** [comment]
Except that we did not enabled yet the full local rendering.

**Comment by BotellaA** [comment]
I did not know about this project. It looks great! :+1: 

I need to read more about ViewStream and their link with ViewProxy but from what I understand, the ViewProxy is either entirely remote or local. Can it be both?

> Except that we did not enabled yet the full local rendering.

Do you have a timeline for this feature or not yet?

**Comment by jourdain** [comment]
We do both (remote/local) right now as the orientation axis is active and managed locally.

We just need to enable the synch of the geometry which is not hard to do. But I don't know when we will be able to enable it.

**Comment by jourdain** [comment]
Like we did in Visualizer
https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Misc/SynchronizableRenderWindow/index.js
https://github.com/Kitware/paraviewweb/blob/master/src/React/Renderers/VtkGeometryRenderer/index.js
https://github.com/Kitware/visualizer/blob/master/src/MainView.js#L5
https://github.com/Kitware/visualizer/blob/master/src/MainView.js#L148-L171
https://github.com/Kitware/visualizer/blob/master/server/pvw-visualizer.py#L199

**Comment by BotellaA** [comment]
I will look at these links.

Thank you and your team for your inspiring work
