### ISSUE TITLE
support loading of file from URL

### ISSUE THREAD

**Issue by jcfr** [Kitware/paraview-glance#232]
Similarly to itk-vtk-viewer, paraview glance should support loading from URL.

For example https://kitware.github.io/itk-vtk-viewer/app/?fileToLoad=https://data.kitware.com/api/v1/file/5b9abb878d777f43cca8aa85/download/collins.nii

Similarly, after loading a sample data(https://kitware.github.io/paraview-glance/app/), the associated URL should be displayed in the URL bar.

cc: @bastienjacquet

**Comment by jourdain** [comment]
https://discourse.paraview.org/t/automatically-load-data-into-paraview-glance/1539
