### ISSUE TITLE
How VtkView re-rendering works?

### ISSUE THREAD

**Issue by BotellaA** [Kitware/paraview-glance#245]
I have a question. I do not understand how the [ToggleDatasetVisibility call](https://github.com/Kitware/paraview-glance/blob/master/src/components/core/Datasets/script.js#L84) can force the re-rendering of the VtkView component. I did not find any event emit from this change.

Thanks for your explanation!

**Comment by jourdain** [comment]
The magic is happening here:
https://github.com/Kitware/paraview-glance/blob/master/src/components/core/App/script.js#L95-L110

So what is happening is the following:
- If a proxy get created/deleted we update the listener list
- If any of our listened proxy get modified the method `proxyManager.autoAnimateViews()` get called except when we load a state file as we only want to render once every piece is actually fully loaded.

**Comment by BotellaA** [comment]
Nice! I love magic! :wink:
