### ISSUE TITLE
VtkView: resizing only working with CSS module?

### ISSUE THREAD

**Issue by BotellaA** [Kitware/paraview-glance#246]
I have my VtkView component that does not scale down when resizing (no issue when scaling up). I tried to reproduce this behavior in paraview-glance to understand the issue. I encounter the same issue with this simplified version of the component.

Code that works:

```
<v-container fluid :class="$style.foo">
  <v-layout column fill-height>
    <v-flex fill-height class="js-view" />
  </v-layout>
</v-container>
```
```
<template src="paraview-glance/src/components/core/VtkView/template.html" />
<style module src="paraview-glance/src/components/core/VtkView/style.css" />
<script src="paraview-glance/src/components/core/VtkView/script.js" />
```
```
.foo {
  position: relative;
  height: 100%;
}
```

Code that does not work:

```
<v-container fluid class="foo"> <-- edit here
  <v-layout column fill-height>
    <v-flex fill-height class="js-view" />
  </v-layout>
</v-container>
```
```
<template src="paraview-glance/src/components/core/VtkView/template.html" />
<style scoped src="paraview-glance/src/components/core/VtkView/style.css" /> <-- edit here
<script src="paraview-glance/src/components/core/VtkView/script.js" />
```
```
.foo {
  position: relative;
  height: 100%;
}
```

I am not good at web development but I was sure these two codes would give the same result. Do you know why it is not the case?

**Comment by BotellaA** [comment]
I tried another test. I was wondering if the attribute `height` of the canvas was preventing to reduce the height of its container. I modified the resize function of the ViewProxy like this:

```  
  publicAPI.resize = () => {
    if (model.container) {
      const dims = model.container.getBoundingClientRect();
      console.log(dims.height);
      model.openglRenderWindow.setSize(0, 0);  <- edit
      const dims2 = model.container.getBoundingClientRect();
      console.log(dims2.height);
      if (dims.width === dims.height && dims.width === 0) {
        return;
      }
      const devicePixelRatio = window.devicePixelRatio || 1;
      const width = Math.max(10, devicePixelRatio * Math.floor(dims.width));
      const height = Math.max(10, devicePixelRatio * Math.floor(dims.height));
      model.openglRenderWindow.setSize(width, height);
      publicAPI.invokeResize({ width, height });
      publicAPI.renderLater();
    }
  };
```

The first output does not want to reduce and always keep the height defined in the canvas.
The second output is correct and if I use it, the resizing works.
I hope this information helps you...

**Comment by floryst** [comment]
Oh, that's because CSS modules will mangle your `.foo` class. If you want to use `class="foo"` in your markup, then you should write `:global(.foo) { ... }` in your CSS.

**Comment by BotellaA** [comment]
Yes, but I changed (for testing purpose) the style tag from `style module` to `style scoped`. In this case, I though `class="foo"` was supposed to work.

**Comment by floryst** [comment]
Ah, I missed that. Does your webpack config for CSS files still use CSS modules ([here is the config](https://github.com/Kitware/paraview-glance/blob/master/build/webpack.base.config.js#L58))? I think CSS modules and scoped tags don't intermix, so you to use scoped you should remove the `modules` option from `vue-style-loader`'s webpack rule.
