### ISSUE TITLE
Render in a div

### ISSUE THREAD

**Issue by finetjul** [Kitware/paraview-glance#271]
How can I get ParaViewGlance to render into a div ? 

Currently it makes the <div> be full screen and breaks a lot of other divs in my page.

**Comment by jourdain** [comment]
I'm guessing you are doing that `const glanceInstance = Glance.createViewer(container);` but it messes up the rest of the page as you don't have a full-screen div?

What are the styles of your div and what is the container app written in?

**Comment by finetjul** [comment]
You are correct, I use `Glance.createViewer(container)`

The whole document is pure HTML (no framework). 
Parent of 'container' is plain display:block <div> that has 2 div children, 2nd child is 'container'.

**Comment by jourdain** [comment]
did you set `position: relative;` to that container div? I'm not sure that would be enough as I think Vuetify makes some assumptions but that should be the bare minimum.

**Comment by finetjul** [comment]
Interestingly enough, simply including `<script ... src="...glance.js">` (not even doing Glance.createViewer()) messes things off. The whole page scrollbar gets frozen.

**Comment by floryst** [comment]
It might be vuetify, but I think another issue is my [global.css](https://github.com/Kitware/paraview-glance/blob/master/static/global.css). I have styles to the html tag to get glance to work nicely with mobile that hopefully I can get rid of with vuetify 2.

**Comment by finetjul** [comment]
@floryst indeed, it is the style for mobile that breaks things. Once I do not include it, then I can nicely tweak the existing style to get PVG to display in a div and not fullscreen.

**Comment by floryst** [comment]
Great. I'll see if I can get rid of that style with the vuetify 2 PR.

**Comment by floryst** [comment]
I think this is resolved now with latest Glance. If not, feel free to re-open.
