### ISSUE TITLE
Bundle of master branch is not stand-alone

### ISSUE THREAD

**Issue by psavery** [Kitware/paraview-glance#285]
There are two issues with this at least:

1. There needs to be an `inline` keyword [here](https://github.com/Kitware/paraview-glance/blob/819176ddbb570ec75f6773e162b8c43a73b22562/static/index.html#L12). Otherwise, the bundled html file searches for a local css file.
2. After number 1 is done, it looks like the bundle is still trying to load web font files locally such as `.woff`, `.woff2`, `.ttf`. These are located in the `dist` directory after building, but they are not included in the bundled html file for some reason.

**Comment by psavery** [comment]
So I figured out that the reason those files are not being included is because of [the limit on the url-loader](https://github.com/Kitware/paraview-glance/blob/819176ddbb570ec75f6773e162b8c43a73b22562/build/webpack.base.config.js#L46-L50). These files are bigger than the limit, so they do not get inlined into the html file.

It looks like if I remove the limit, the files get included, but the paraview glance size is ~7 MB. Is this too large?

@floryst

**Comment by jourdain** [comment]
Why is Glance that fat? It was 3MB so far...

**Comment by psavery** [comment]
If I don't modify the line for the limit of the `url-loader`, then Glance is ~3.3 MB. But it excludes the following font files (size from `du -h` is printed on the left):

```
356K	a0d13d16cc2f3647680d9f1ff003f58b.woff
252K	7ec5dab7e7ff250971d2ff50379778dc.woff2
740K	3ac50b5b36eb2f11b000dce1792d0bb0.ttf
```

They might be bigger in base64 encoding, not sure. But including these font files is what makes it go up to ~7 MB I think. These are the font files for the icons from [here](https://github.com/Templarian/MaterialDesign-Webfont/tree/master/fonts).

**Comment by jourdain** [comment]
Technically only one is needed.

**Comment by psavery** [comment]
Ah yeah I see. I think we will just need to raise the size limit so that only one of them is included, and then it will hopefully be good to go!

**Comment by psavery** [comment]
Yep, looks like I need to raise the url-loader limit to ~300KB, and then a single font file gets included, there are no errors, and the Glance file is ~3.7 MB!
