### ISSUE TITLE
The edges of the image drawn by Paint are not smooth.

### ISSUE THREAD

**Issue by HuWei501** [Kitware/paraview-glance#293]
The edges of the image drawn by Paint are not smooth, like this:
![image](https://user-images.githubusercontent.com/19411208/72578220-67165c00-3910-11ea-8a6a-414558976e8b.png)
How to fix it?

**Comment by floryst** [comment]
Hi, the edges aren't smooth because the vtk.js paint widget is meant to paint labelmaps, and currently doesn't support antialiased painting.

**Comment by HuWei501** [comment]
if I need to support antialiased painting, is there any good way?

**Comment by floryst** [comment]
Off the top of my head, you would have to make your own version of the [vtkPaintFilter](https://github.com/Kitware/vtk-js/blob/master/Sources/Filters/General/PaintFilter/index.js) (along with the PaintFilter.worker.js) that, given a coordinate, draws your desired shape (e.g. ball) with antialiasing. In addition, you will need to decide how to encode semi-transparent pixels in the underlying vtkImageData, and deal with blending if you have multiple colors.

We currently do not have a need for antialiased paint in vtk.js, but if you want to take a shot at implementing and contribute then I'll be glad to help look over what you have. :)

**Comment by HuWei501** [comment]
Yes, I am trying to encode semi-transparent pixels in the underlying vtkImageData, do you have the relevant documentation?

**Comment by floryst** [comment]
You can encode them however you want. vtkImageData only stores pixel data. Rendering-wise, you will have to look at vtkImageMapper's scalarOpacity field, which will allow you to define a vtkPiecewiseFunction that maps pixel values to opacity for rendering.
