### ISSUE TITLE
How to specify a local Girder URL?

### ISSUE THREAD

**Issue by imilos** [Kitware/paraview-glance#303]
I want to use a local Girder server, but when I go for Open->Girder, I can only see collections on the Kitware Girder instance. Is it possible to use my local Girder instance and how?

**Comment by floryst** [comment]
@HastingsGreer will look into specifying a local girder server.

**Comment by HastingsGreer** [comment]
Hi! In the latest nightly build, it is possible to specify a different server using a URL parameter. For example, localhost can be used at the url [https://kitware.github.io/paraview-glance/nightly/?girderRoute=http://localhost:9000/api/v1](https://kitware.github.io/paraview-glance/nightly/?girderRoute=http://localhost:9000/api/v1)

Thank you for bringing this to our attention!

**Comment by imilos** [comment]
Many thanks for your quick response! However, I immediatelly tried your new development using my own remote Girder endpoint, https://kitware.github.io/paraview-glance/nightly/?girderRoute=http://silicofcm-test.bioirc.ac.rs:8888/api/v1. However, I'm getting the error message :(

**Comment by HastingsGreer** [comment]
Hi! There are two steps to allow paraview glance to interface with your girder server:

1: Girder and Glance must either both be http, or both be https. The easiest fix for this is to use an http instance of paraview glance, such as by hosting it on localhost. The trickier but better solution is to enable https on your girder server. I'm looking for good documentation on how to do that, and will get back to you.

2: Girder must have CORS turned on, which is a security setting that can enable other websites (such as paraview glance) to make calls to your girder api endpoints. [Here](https://girder.readthedocs.io/en/stable/security.html#cors-cross-origin-resource-sharing) you can find documentation on how to update this setting.

Thanks for helping us debug this! We had not noticed the issue with http and https until you reported this bug.

**Comment by imilos** [comment]
It is working! Thanks a lot! I'm closing the issue now.
