### ISSUE TITLE
XYZ box changed to LPS box when load medical images

### ISSUE THREAD

**Issue by aylward** [Kitware/paraview-glance#33]

**Comment by agirault** [comment]
Can make use of that preset: https://github.com/Kitware/vtk-js/blob/38d5e4faaa97e080d28fd242b4efcebaf2307a0d/Sources/Rendering/Core/AnnotatedCubeActor/Presets.js#L38

**Comment by floryst** [comment]
This is handled by app modes.

**Comment by floryst** [comment]
We have the option to manually toggle XYZ/LPS box in v2.
