### ISSUE TITLE
Stable and nightly release links do not work

### ISSUE THREAD

**Issue by ronzim** [Kitware/paraview-glance#348]
Both give 404 error.

**Comment by liangwang0734** [comment]
Possibly relevant issue: I cannot see anything in the default app at https://kitware.github.io/paraview-glance/app/index.html/ on both Linux and Android Chrome.

**Comment by ziqiangxu** [comment]
I have the same problem for several days。

**Comment by floryst** [comment]
Thanks for the reports. I'm looking into it, and for some reason there is now a http redirect to `/index.html/` (note the trailing slash).

**Comment by floryst** [comment]
Still an issue. From the failure of the last merge, I narrowed down the issue to the travis build cache. I'm moving to github actions.

**Comment by floryst** [comment]
This is now fixed.
