### ISSUE TITLE
Colored slice view?

### ISSUE THREAD

**Issue by liangwang0734** [Kitware/paraview-glance#351]
Presently all example (image) data are rendered in black-and-white in the `Slice` view.
Is it a planned feature to allow showing colored slices?

**Comment by floryst** [comment]
What sort of image are you visualizing? I don't have any multi-component volumes on hand to test, but loading 2D JPEGs (and viewing them on the Z axis) show color, albeit a bit transparent by default due to the windowing level.

**Comment by floryst** [comment]
If you're referring to applying the color transfer function (that you see in the 3D view) to the 2D slices, then that might be something to consider as a toggle. But I don't know how useful that would be off the top of my head.

**Comment by liangwang0734** [comment]
> If you're referring to applying the color transfer function (that you see in the 3D view) to the 2D slices, then that might be something to consider as a toggle. But I don't know how useful that would be off the top of my head.

Hi Forrest. Yes, I was referring to applying the color transfer function (that I see in the 3d view) to the 2D slices. Therefore, a toggle would be ideal.
This is a common scenario in our scientific computing data visualization. For example, in 3d, we show volume rendering, and in 2d slices, we show color-coded contours using the same colormap.

An example, in the following ParaView visualization, we present two slices to show the formation of structures in a simple way: https://www.nas.nasa.gov/SC19/assets/images/content/7_Dong_C_SC19_1_big.png

**Comment by jourdain** [comment]
Those slices could be made with "Slice" filter in PV. The only thing that will be missing would be the "transparency part" of the color map for that field. But that could be faked by clipping by scalars those slice as well.

**Comment by liangwang0734** [comment]
Yes, Sebastien. I agree doing the slicing in PV + toggling slices in Glance is a good solution.

Nevertheless, I think allowing color mapping in Glance's slice view would be a very useful feature liked by many scientific computing people :)

**Comment by jourdain** [comment]
I agree with the color map for slices. But those features were driven by medical needs initially. But I'm sure @floryst can figure out something and provide a toggle to enable it.

**Comment by floryst** [comment]
This is now implemented, with an extra option that independently toggles opacity and color.
