### ISSUE TITLE
If two geometry files are loaded, and they color by same scalars name, here is a problem?

### ISSUE THREAD

**Issue by ziqiangxu** [Kitware/paraview-glance#358]
I have loaded two geometry files, they are like this.

1. Vessel.vtk
![image](https://user-images.githubusercontent.com/18530271/89393971-0fb9cb00-d73e-11ea-8e17-772353a416ef.png)
2. Segmentation.vtk
![image](https://user-images.githubusercontent.com/18530271/89394006-1d6f5080-d73e-11ea-9540-ee884c87d53c.png)

When I show them at the same time and all color by `scalars`. It will like this, they are rendering by one colormap.
![image](https://user-images.githubusercontent.com/18530271/89394343-8ce54000-d73e-11ea-91f3-55bd3b5a2e5f.png)

It seems that they are using the same ~representation~lookupColorTable(I have read the code), is it a deliberate design？

**Comment by floryst** [comment]
This is by design. Internally, arrays of the same name use the same lookup table. I believe this mimics the functionality of ParaView. (@jourdain please correct me if I'm wrong by any chance.)

**Comment by ziqiangxu** [comment]
> This is by design. Internally, arrays of the same name use the same lookup table. I believe this mimics the functionality of ParaView. (@jourdain please correct me if I'm wrong by any chance.)

OK, thanks for your reply. BTW, now glance's painting has only one 3D mode, actually, the 2D mode may more useful, is it in the TODO list?

**Comment by jourdain** [comment]
Same field name should have a shared color scale otherwise you could not compare the temperature of 2 objects accurately. If you want to get independent coloring for meshes, you should not name your field `scalars` everywhere. You could use the name of your geometry assuming that one is unique.

**Comment by jourdain** [comment]
They are not using the same `representation` but the same `LookupColorTable` to allow user to compare Apple to Apple.

**Comment by ziqiangxu** [comment]
I see, thank you very much.
