### ISSUE TITLE
Now glance's painting has only one 3D mode, actually, the 2D mode may more useful, is it in the TODO list?

### ISSUE THREAD

**Issue by ziqiangxu** [Kitware/paraview-glance#359]

**Comment by floryst** [comment]
Yes, that would be useful. The underlying paint widget already supports 2D mode, so hopefully it won't be too much of an effort to add it in. I'll look to add it in when I get the chance.

**Comment by ziqiangxu** [comment]
> Yes, that would be useful. The underlying paint widget already supports 2D mode, so hopefully it won't be too much of an effort to add it in. I'll look to add it in when I get the chance, unless you would like to take a shot at it (check out vtk.js vtkPaintWidget and vtkPaintFilter).

I am looking forward to your great work. And I'm not familiar with vtk.js, but I will look into this, thank you very much.
