### ISSUE TITLE
Reset camera when using tool

### ISSUE THREAD

**Issue by thomas-beznik** [Kitware/paraview-glance#365]
The behavior of the camera reset is different when using a tool; the image is not centered in the same way.

This is without activating a tool:
![Screenshot 2020-08-25 at 16 14 38 (3)](https://user-images.githubusercontent.com/53873742/91185921-adc20500-e6ee-11ea-8c4a-0ead57acabb4.png)

This is with a tool activated:
![Screenshot 2020-08-25 at 16 14 55 (3)](https://user-images.githubusercontent.com/53873742/91185889-a4389d00-e6ee-11ea-927e-caa56d2e7447.png)

When digging more into it, it seems like the focal point of the camera is different when using a tool. Do you know why this is the case? How can this be fixed? Thanks!

**Comment by floryst** [comment]
I can't seem to reproduce this. I'm opening an image, zooming in and panning, then turning on paint, and then resetting the camera (both via the button and the key "R"), and it resets for me. Is there some different sequence of actions that result in this undesired behavior?

**Comment by thomas-beznik** [comment]
The problem is not that the camera isn't reset, but that when resetting it centers the image differently when the tool is activated compared to when it's not. I zoomed in in order to make this effect more apparent than when the image is totally zoomed out. Here are the steps:

1. Zoom to have the image fit the screen.
2. Activate the paint tool.
3. Click on the reset camera button.
4. Zoom to have the image fit the screen. You should see that the image is translated compared to step 1.

Even without zooming in, if you take the "Tooth" sample and reset the camera with and without the paintbrush activated, you will see the image moving. In this case, the translation is very small, while for my image it is much more noticeable:


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/53873742/91533792-c9a4f100-e910-11ea-8112-a6d09317e11f.gif)
