### ISSUE TITLE
Listeners on paintWidget are not working correctly

### ISSUE THREAD

**Issue by a3VonG** [Kitware/paraview-glance#366]
Hi I noticed the following edge case when using the paintTool, you can reproduce the bug as follows:

1. Activate the paint tool
2. Start painting holding left mouse down
3. While the left mouse is down press the right click
4. Release the right click
5. Release the left click
This should put you in an always paint mode (which can be easily deactivated by clicking again). 

It seems that for some reason the handleLeftButtonRelease is not called anymore in the paintWidget when performing step 5. Any ideas on how to solve it?

**Comment by floryst** [comment]
This appears to be a bug with vtk.js incorrectly handling multiple buttons at the same time.

**Comment by a3VonG** [comment]
I'll open an issue there, it's on other widgets as well.

**Comment by floryst** [comment]
By the way, this should be fixed now.
