### ISSUE TITLE
Some .dcm files don't work on chrome/firefox but do work on safari 

### ISSUE THREAD

**Issue by a3VonG** [Kitware/paraview-glance#367]
I was trying to upload this dicom slice (included here as a zip so first unzip before trying). 
[image-00000.dcm.zip](https://github.com/Kitware/paraview-glance/files/5125930/image-00000.dcm.zip)

On chrome and firefox I'm unable to load this slice and it seems to be stuck on the loading. I don't receive any error messages however.  On safari the app loads in the slice perfectly. 
Any ideas on how this could be fixed? 

Thank you!

**Comment by floryst** [comment]
I will check this out. Thanks for the report!

**Comment by floryst** [comment]
I don't have Safari to test things out, but initial research on Chrome points to cross-compiled GDCM from itk.js as being the underlying issue. It spin-waits while waiting for a thread, but there are no threads. This isn't a problem with GDCM per-say, but rather an artifact of cross-compiling. Not sure why it loads on Safari, however.

**Comment by floryst** [comment]
Update: I have a workaround for upstream itk-js that fixes this issue. Once a PR is made there, I'll then link to this issue.
