### ISSUE TITLE
lidar.vtp fails to be loaded in ParaViewGlance demo

### ISSUE THREAD

**Issue by finetjul** [Kitware/paraview-glance#372]
On https://kitware.github.io/paraview-glance/app/, here is the error preventing ParaViewGlance to load: 
![image](https://user-images.githubusercontent.com/219044/93309090-64ec0080-f803-11ea-9995-e17033e09bc4.png)

**Comment by floryst** [comment]
Can you try force-refreshing? It happened to me once, and then when I emptied cache and then reloaded it worked for me.

**Comment by finetjul** [comment]
Yes a force refresh (CTRL + SHIFT + R) makes it work the second time.
However if I close the tab and create a new tab again, I still have the issue.
I wonder if there is a timing issue (data is not available when worker is instantiated or something like that?)

**Comment by floryst** [comment]
I can't seem to reproduce this anymore. Does it occur on nightly? If not then I will update stable to nightly.

**Comment by finetjul** [comment]
Seems that it is fixed in stable. Thanks.
