### ISSUE TITLE
Error loading a JSON

### ISSUE THREAD

**Issue by devngc** [Kitware/paraview-glance#381]
ParaViewGlance: 4.9.13
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

```
Uncaught TypeError: e.getDataset(...).isA is not a function
```

**Comment by floryst** [comment]
Glance doesn't load arbitrary JSON by default, as there has to be a specific reader for it.
