### ISSUE TITLE
Running Paraview Glance on production mode

### ISSUE THREAD

**Issue by MrunalNasery** [Kitware/paraview-glance#383]
Steps to be followed to run app in production mode

**Comment by floryst** [comment]
Thanks for the report! I'll add steps to the readme. In the meantime, here is a sketch of deploying the app to prod:
1. Run `npm run build:release``. This will output files into `dist/`
2. Copy the files from `dist/` to your desired web hosting location.

**Comment by MrunalNasery** [comment]
Thank you. I am using http-server to serve files. But, i get sockjs-node/info?t={} 404 Error. 
My host is not secure. Is that the reason for the above error? Or is there something else I am missing?

**Comment by floryst** [comment]
I cannot reproduce this. I've done the following steps:
```
npm run build:release
cd dist/
npx http-server
```

I believe sockjs is used with hot-module reloading, so it appears taht you are still somehow getting the development build files. If you are still having this issue, can you please provide reproduction steps?
