### ISSUE TITLE
.vtkjs files are not supported when loading from Girder API

### ISSUE THREAD

**Issue by finetjul** [Kitware/paraview-glance#389]
For some reason, it is not possible to load .vtkjs file by using the Girder loader.
It works fine when loading a local file

**Comment by floryst** [comment]
Hm, is there a public dataset on girder to test? I can't think of anything specific that would cause this.

**Comment by finetjul** [comment]
https://data.kitware.com/#item/60673a4e2fa25629b9472154

**Comment by RemDelaporteMathurin** [comment]
@finetjul Don't know if this is still an issue but this link opens your file

https://kitware.github.io/paraview-glance/app/?name=[mine.vtkjs]&url=[https://data.kitware.com/api/v1/file/60673a582fa25629b947215b/download]

![image](https://user-images.githubusercontent.com/40028739/162738192-e2dd7dc5-c8a4-412c-abdb-f648c7fc13f1.png)

**Comment by finetjul** [comment]
Looks like it's fixed/closed.
