### ISSUE TITLE
Can't keep "Solid Color" in export from Paraview 

### ISSUE THREAD

**Issue by liamtimms** [Kitware/paraview-glance#408]
Hi,

I am attempting to export a scene from Paraview desktop into Paraview Glance. In the simplest case, I have a `.vtp` surface which I am selecting to display as a "Surface" in Paraview with coloring defined as "Solid Color" and a color selected from the "Basic Colors" provided in the Paraview color picker. I can successfully export this scene into an embedded Paraview Glance instance `.html` file using the procedure outlined here: https://blog.kitware.com/exporting-paraview-scenes-to-paraview-glance/ 

However, when loaded the display always defaults to a "Scalars_" coloring and the "solid color" option must be manually selected to recover the intended representation. The following errors are given: 

ParaViewGlance: 4.17.1
Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0

```
attempt to set zero width color range
attempt to set zero width color range
attempt to set zero width color range
```

There does not appear to be an issue with the solid color representation once it is manually selected, it displays as intended.  However in cases where we have multiple surfaces, asking each viewer to manually change each individual surface to a "Solid Color" is unreasonable. 

An example of the html is available here: https://liamtimms.net/paraview/test_simple_artery.html

**Comment by liamtimms** [comment]
Workaround is setting up and saving glance displays directly instead.

**Comment by hbraunDSP** [comment]
My team has encountered what I believe is the same bug. I opened a new issue at #504.
