### ISSUE TITLE
Sample data doesn't seem to load

### ISSUE THREAD

**Issue by ebrahimebrahim** [Kitware/paraview-glance#410]
When I click on any of the sample data [here](https://kitware.github.io/paraview-glance/app/) in firefox or chrome, I end up getting the file upload dialog, the same one I get when I click the "open a file" button.

**Comment by jourdain** [comment]
The latest version seems fine.
https://kitware.github.io/paraview-glance/nightly/

**Comment by ebrahimebrahim** [comment]
Hmm, the latest version works for me as well, while the one I linked doesn't. Please feel free to close if that means it's an already-fixed problem and the app that I linked will be updated later.

**Comment by jourdain** [comment]
I'm not sure why just yet but @floryst might be interested to double check why and bump the __stable__ version... So keeping it open for now. Thanks for the report.
