### ISSUE TITLE
Cannot open large VTP file

### ISSUE THREAD

**Issue by aylward** [Kitware/paraview-glance#411]
When attempting to load the attached large VTP file, I get the error
![image](https://user-images.githubusercontent.com/279727/133778437-6f28486d-3ae6-4a5e-b90a-e18a9bb7540e.png)

The VTP file is attached.

Thanks!

[diff3-Vessels.zip](https://github.com/Kitware/paraview-glance/files/7185368/diff3-Vessels.zip)

**Comment by jourdain** [comment]
Just tested with Glance without itk.js (standalone html) and the file loads (Meaning it is a valid file). I'm not sure what is going on with the itk.js reader here. Hopefully @thewtex or @floryst can help.

**Comment by floryst** [comment]
This should now be fixed in master and stable.
