### ISSUE TITLE
Parameter in URL is not working 

### ISSUE THREAD

**Issue by finetjul** [Kitware/paraview-glance#419]
In current deployed release parameter in url has stopped working.
e.g.
https://kitware.github.io/paraview-glance/app/?name=diskout.vtp&url=https://data.kitware.com/api/v1/item/59de9de58d777f31ac641dc5/download

**Comment by floryst** [comment]
I think this is a result of caching, since that link works for me. I've updated the caching strategy, since I got it wrong the first time.

**Comment by finetjul** [comment]
Thanks
