### ISSUE TITLE
vtkjs file from url not loading.

### ISSUE THREAD

**Issue by buckettt** [Kitware/paraview-glance#425]
When loading a .vtkjs file from a url I get the "loading resources from url..." message and then it just returns to the home/examples page. Even when running everything locally. I'm building the latest version from github.  

e.g. http://localhost:8000/?name=export.vtkjs&url=http://localhost:5000/api/mesh/downloadvtkjs/spectral-chipmunk
(glance is on 8000, files are served on 5000)

Downloading the same file to disk and then opening manually works fine and as expected.

Any idea what the differences might be?

**Comment by buckettt** [comment]
UPDATE: The vtkjs is being loaded fine. It's actually that the landing page doesn't hide automatically and clicking on the Logo/Go To App hides the issue.

**Comment by floryst** [comment]
The issue was certain vtkjs files could have no lookup tables. This is now fixed in master.
