### ISSUE TITLE
Cannot upload to Girder

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [Kitware/paraview-glance#426]
Hi all!

thanks for that very nice tool!

I would like to embed a paraview glance window into a presentation therefore I need my file to be accessible via a link.

It seems that Girder is the only solution at the moment.

Unfortunately I wasn't able to upload anything there.

To reproduce:

1. Go to https://kitware.github.io/paraview-glance/app/?name=[cow.vtp]&url=[https://data.kitware.com/api/v1/file/5afd936e8d777f15ebe1b4ea/download]

2. Click on the three dots next to cow.vtp

3. Click Upload to Girder
The following pops up:
![image](https://user-images.githubusercontent.com/40028739/159472819-d2c04f44-dfbd-4dc8-81ea-fd590e7676ae.png)

5. Click Public then Cancel
![image](https://user-images.githubusercontent.com/40028739/159473226-d1d22c14-c98d-49e9-91e3-96554cd70df6.png)

3. Click Upload to Girder again
Now a window with Uploading appears but hangs forever and nothing is uploaded.
Note: the close button doesn't work...
![image](https://user-images.githubusercontent.com/40028739/159473279-57302be9-08b8-4504-86b7-a9c1353a16eb.png)

Any idea how to upload something to Girder easily?

Thanks in advance for the help!

Rem

**Comment by floryst** [comment]
This should be fixed in master now with https://github.com/Kitware/paraview-glance/commit/8b3e5c46e15e7b1d4c5c0227cfb7bc31156c0279. Stable will be updated shortly.
