### ISSUE TITLE
Opacity rendering bug

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [Kitware/paraview-glance#428]
Hi @floryst 

https://kitware.github.io/paraview-glance/app/?name=[WCLL_temperature.vtkjs]&url=[https://data.kitware.com/api/v1/item/62444fcd4acac99f423de89d/download]

On this dataset the opacity is a bit weird.

Here's what's produced in Glance:

![image](https://user-images.githubusercontent.com/40028739/160837580-a173b917-04a1-4b98-a231-84e8d640310f.png)

Here's what's produced in Paraview:
![image](https://user-images.githubusercontent.com/40028739/160837632-7184e0ee-5b55-49cc-aa6b-ce1dda7bb1da.png)

Is this a bug related to vtkjs?

**Comment by floryst** [comment]
It is. This was recently fixed in vtk.js; I will have to see about upgrading Glance's vtk.js version.
