### ISSUE TITLE
Control the blending between two (or more) volumes as displayed in the 2D slice view render window

### ISSUE THREAD

**Issue by aylward** [Kitware/paraview-glance#80]
When multiple volumes are rendered into a 2D view, there should be a primary volume (which controls the concept of next/previous/current slice through space, and the orientation of that slice, e.g., x-y, y-z, x-z) and there could be secondary volumes that are shown based on intersecting the primary slice with those volumes.   Primary and secondary volumes can have varying opacities.

**Comment by floryst** [comment]
This technically exists now, where slices are all synchronized. Additionally, each slice has its own opacity slider.
