### ISSUE TITLE
Cannot read STL file

### ISSUE THREAD

**Issue by aylward** [Kitware/paraview-glance#95]
When dragging and dropping or opening an STL file, PVG reports "Specified file is not currently supported" and then brings up a raw image reader dialog that reports "Effective size does not match total size!"

A sample file is at:
https://gitlab.kitware.com/cmb/smtk/blob/master/data/model/3d/stl/kettle.stl

This bug was reported by 
Haocheng Liu

**Comment by jourdain** [comment]
vtk.js only support binary stl files. We never get a chance to implement the text version of that format.

**Comment by jourdain** [comment]
vtk.js 7.0.1 bring that support
